# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 15:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180619_1440'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('ordered_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
